### ISSUE TITLE
Error 126

### ISSUE THREAD

**Issue by vullnetlimani** [Magisk-Modules-Alt-Repo/data_backup#8] opened 2023-06-09 17:29 UTC
I am not using my phone, Airplane is on, and I am using my PC to start the script.

This is the log:

```
eqs:/ # data_backup.sh
Loading...
/system/bin/data_backup.sh[17]: /dev/temp/bbx/busybox: can't execute: Permission denied

****************************************************
*            User Data backup creator              *
*                v2.13 by @ziand                   *
*                     *****                        *
* usage: data_backup.sh [-M] [-e <p1>..] [-m] [-h] *
* -M  Multy-volume backup by up to 4GB for FAT32   *
* -e <path1> <path2> <...>   backuping without one *
*     or more paths of internal SD                 *
* -m  backuping without all content of internal SD *
* -h  Show help message and exit                   *
****************************************************

Date: 2023-06-09--19-27-52
Build info: eqs_g-user 12 S3SQS32.16-72-32-3 78734-4a083
Backup with intSD: Yes
Magisk version: fdac22ba-delta (25210)

Any external storage device not mounted
Creating backup to folder:
/data/media/0/databackup


Data backup is not created properly.
Backup is deleted. Try backuping again.
During backuping, do not use the device
and do not switch off the screen.

Failure. Error 126
```

**Comment by ziandzivan** [comment] 2023-06-10 12:04
> and I am using my PC to start the script.

It doesn't matter where you are running the script from.
I think the problem is due to old utilities on your phone, toy/busybox. Try this script and inform how it works:
[data_backup_v2.13-test-03-MAGISK.zip](https://github.com/Magisk-Modules-Alt-Repo/data_backup/files/11712314/data_backup_v2.13-test-03-MAGISK.zip)
thanks

P.S. I wouldn't use the fork of Magisk - delta. In the past I had to make few corrections in the script for the delta, customize.sh in the module also was needed for some users with it. It is developing on the official Magisk stable or canary version.

**Comment by vullnetlimani** [comment] 2023-06-10 13:50
I had the same log from both repos that for raised the bug here.
By the way I am using busy box by zgfg @ xda 1.0.6 should I use any other version or that's fine?

I've tried your test module it's working I have like 220MB/s speed on average that's dope.

So this is working same as TWRP backup because on my Motorola 30 ultra edge I don't have TWRP, but I want to try ROMs, but then I hate to install everything from the beginning because I cannot back up and restore same way as I was doing with TWRP back in time.

So you right now most I can do is backup over swift back up and then accounts needs to be restored back.

So this would back up everything on my phone and then when I restore I would have it as it was, correct.

Here are the logs:

```
eqs:/ $ su
eqs:/ # data_backup.sh
Loading...

****************************************************
*            User Data backup creator              *
*                v2.13 by @ziand                   *
*                     *****                        *
* usage: data_backup.sh [-M] [-e <p1>..] [-m] [-h] *
* -M  Multy-volume backup by up to 4GB for FAT32   *
* -e <path1> <path2> <...>   backuping without one *
*     or more paths of internal SD                 *
* -m  backuping without all content of internal SD *
* -h  Show help message and exit                   *
****************************************************

Date: 2023-06-10--15-47-13
Build info: eqs_g-user 12 S3SQS32.16-72-32-3 78734-4a083
Backup with intSD: Yes
Magisk version: fdac22ba-delta (25210)

Any external storage device not mounted
Creating backup to folder:
/data/media/0/databackup

Totals: 44559872000 bytes, 179 seconds, 237 MB/sec.

Data backup is created successfully.
Running calculating checksum in the background...

Script is finished.
```

**Comment by ziandzivan** [comment] 2023-06-10 17:54
> I am using busy box by zgfg @ xda 1.0.6 should I use any other version or that's fine?

I am not familiar with it. I can offer you @osm0sis's busybox:
https://github.com/Magisk-Modules-Repo/busybox-ndk
https://forum.xda-developers.com/t/tools-zips-scripts-osm0sis-odds-and-ends-multiple-devices-platforms.2239421/page-21#post-64228091

> So this would back up everything on my phone and then when I restore I would have it as it was, correct.

Yes. 
This will restore everything... accounts, apps, your OS and apps settings... and so on.
The backup with intSD is preferred for restoring messagers, some other apps, ..

Ok, thanks for your info. It will be included to next script version.

**Closed** 2023-06-12 04:07 UTC
